# -*- coding: utf-8 -*-
"""aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwmoFpNFRyZjQh2gzbTh1kvioxS6Wv1m
"""

resposta = input('deseja ir para proxima tela:')
if resposta =='sim':
 print('vc esta sendo direcionado para px tela')
else:
  print('progama finalizado')



nome=  input('informe seu nome:')
sexo= input("informe'M'para masculino e 'F' para feminino").upper()
if (sexo=='M'):
    sexo= 'o'
elif (sexo== 'F'):
    sexo= 'a'
usuario= int(input('informe o tipo de usuario \n1-para administrador \n2 - para usuario comum \n 3 - para menbro associado:'))
if ( usuario == 1):
    usuario = 'adminstradror do sistema'
elif(usuario==3):
    usuario= 'menbro associado'
elif(usuario==2):
    usuario= 'usuario comum'

else:
    usuario= 'usuario nao cadastrado'

print(f'seja bem vind{sexo} {nome}, a sua licença e de {usuario}')